"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
require("./globals.css");
const providers_1 = require("./providers");
exports.metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
function RootLayout({ children, }) {
    return (<html lang="en">
      <body>
        <providers_1.Providers>
          {children}
        </providers_1.Providers>
      </body>
    </html>);
}
exports.default = RootLayout;
